version: '3'

services:
  web:
    build: ./web/Dockerfile.dev
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api
  api:
    build: ./src/Dockerfile
    ports:
      - "8000:8000" # デバグ用
