version: '3'

services:
  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/my-app.conf
    restart: always
    depends_on:
      - api
  api:
    build: ./src
    ports:
      - "8000:8000"
